version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - elasticsearch
    environment:
      WAIT_HOSTS: elasticsearch:9200
    ports:
      - "8080:8080"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.0"
    environment:
      discovery.type: "single-node"
      cluster.name: "cluster-1"
      node.name: "node-1"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
volumes:
  esdata:
 